#1.5 unidades de CPU e 550MB
version: "3.5"

services:
  api01: &api
    build:
      context: ./.docker/prd
      dockerfile: prd.Dockerfile
    volumes:
      - ./:/var/www/app
    hostname: api01
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - API_USE_DB_FUNC=true
      - PORT=3000
      - DB_DATABASE=rinha
      - DB_USERNAME=admin
      - DB_PASSWORD=123
    ports:
      - "3001:9501"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '65MB'

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3002:9501"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '60MB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '360MB'

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
