name: Deploy production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: glauberborges
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            glauberborges/rinha-q1-2024:latest
            glauberborges/rinha-q1-2024:${{ github.ref_name }}-${{ github.sha }}
          context: .
          file: ./.docker/prd/prd.Dockerfile
